# Generated by Django 6.0.5 on 2026-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
